stickers = [
    'CAACAgIAAxkBAAEU8SppUUZJ9ydGr9mWI-ALOvHwYelKFwACa2MAAr-JSUh-asjk6ghxojYE',
    'CAACAgIAAxkBAAEU8RZpUUPVDLhNTDjDrPaUWbPU0onp4wACmzoAAol4oEhdeAABUb09zg42BA',
    'CAACAgIAAxkBAAEU8XRpUVt42djMhmzvc2r1ac-_57MeUQACJoMAAnn_6UjwHVhkCrQKCTYE',
    'CAACAgIAAxkBAAEU8XZpUVt-wse_8OH-rN1HPZHlYlgUiQACyYUAAvWWEEmqkdMaJgrYgTYE',
    'CAACAgIAAxkBAAEU8XhpUVuMHTHM1D_PTmp2CLTBPxtOHgACi08AAg0gMUt9l9QmGMb-YDYE',
    'CAACAgIAAxkBAAEU-TtpU9TTgHTJ-gMym76k53hGkaTRpAAC5n0AAkhceElWFj93gg89wDgE',
    'CAACAgIAAxkBAAEU-T1pU9T_0g-04lMJNOtlG4KgTyzBagACqnsAAtRxaUpLtgjw97rGpDgE'
]